# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cchaumar/Documents/42projects/working/_corewar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cchaumar/Documents/42projects/working/_corewar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cchaumar/Documents/42projects/working/_corewar/CMakeFiles /Users/cchaumar/Documents/42projects/working/_corewar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cchaumar/Documents/42projects/working/_corewar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asm

# Build rule for target.
asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asm
.PHONY : asm

# fast build rule for target.
asm/fast:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/build
.PHONY : asm/fast

#=============================================================================
# Target rules for targets named corewar

# Build rule for target.
corewar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 corewar
.PHONY : corewar

# fast build rule for target.
corewar/fast:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/build
.PHONY : corewar/fast

srcs/asm_srcs/asm.o: srcs/asm_srcs/asm.c.o

.PHONY : srcs/asm_srcs/asm.o

# target to build an object file
srcs/asm_srcs/asm.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm.c.o
.PHONY : srcs/asm_srcs/asm.c.o

srcs/asm_srcs/asm.i: srcs/asm_srcs/asm.c.i

.PHONY : srcs/asm_srcs/asm.i

# target to preprocess a source file
srcs/asm_srcs/asm.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm.c.i
.PHONY : srcs/asm_srcs/asm.c.i

srcs/asm_srcs/asm.s: srcs/asm_srcs/asm.c.s

.PHONY : srcs/asm_srcs/asm.s

# target to generate assembly for a file
srcs/asm_srcs/asm.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm.c.s
.PHONY : srcs/asm_srcs/asm.c.s

srcs/asm_srcs/asm_tokens.o: srcs/asm_srcs/asm_tokens.c.o

.PHONY : srcs/asm_srcs/asm_tokens.o

# target to build an object file
srcs/asm_srcs/asm_tokens.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm_tokens.c.o
.PHONY : srcs/asm_srcs/asm_tokens.c.o

srcs/asm_srcs/asm_tokens.i: srcs/asm_srcs/asm_tokens.c.i

.PHONY : srcs/asm_srcs/asm_tokens.i

# target to preprocess a source file
srcs/asm_srcs/asm_tokens.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm_tokens.c.i
.PHONY : srcs/asm_srcs/asm_tokens.c.i

srcs/asm_srcs/asm_tokens.s: srcs/asm_srcs/asm_tokens.c.s

.PHONY : srcs/asm_srcs/asm_tokens.s

# target to generate assembly for a file
srcs/asm_srcs/asm_tokens.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/asm_tokens.c.s
.PHONY : srcs/asm_srcs/asm_tokens.c.s

srcs/asm_srcs/compile.o: srcs/asm_srcs/compile.c.o

.PHONY : srcs/asm_srcs/compile.o

# target to build an object file
srcs/asm_srcs/compile.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/compile.c.o
.PHONY : srcs/asm_srcs/compile.c.o

srcs/asm_srcs/compile.i: srcs/asm_srcs/compile.c.i

.PHONY : srcs/asm_srcs/compile.i

# target to preprocess a source file
srcs/asm_srcs/compile.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/compile.c.i
.PHONY : srcs/asm_srcs/compile.c.i

srcs/asm_srcs/compile.s: srcs/asm_srcs/compile.c.s

.PHONY : srcs/asm_srcs/compile.s

# target to generate assembly for a file
srcs/asm_srcs/compile.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/compile.c.s
.PHONY : srcs/asm_srcs/compile.c.s

srcs/asm_srcs/op.o: srcs/asm_srcs/op.c.o

.PHONY : srcs/asm_srcs/op.o

# target to build an object file
srcs/asm_srcs/op.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/op.c.o
.PHONY : srcs/asm_srcs/op.c.o

srcs/asm_srcs/op.i: srcs/asm_srcs/op.c.i

.PHONY : srcs/asm_srcs/op.i

# target to preprocess a source file
srcs/asm_srcs/op.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/op.c.i
.PHONY : srcs/asm_srcs/op.c.i

srcs/asm_srcs/op.s: srcs/asm_srcs/op.c.s

.PHONY : srcs/asm_srcs/op.s

# target to generate assembly for a file
srcs/asm_srcs/op.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/op.c.s
.PHONY : srcs/asm_srcs/op.c.s

srcs/asm_srcs/opt_tokens.o: srcs/asm_srcs/opt_tokens.c.o

.PHONY : srcs/asm_srcs/opt_tokens.o

# target to build an object file
srcs/asm_srcs/opt_tokens.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/opt_tokens.c.o
.PHONY : srcs/asm_srcs/opt_tokens.c.o

srcs/asm_srcs/opt_tokens.i: srcs/asm_srcs/opt_tokens.c.i

.PHONY : srcs/asm_srcs/opt_tokens.i

# target to preprocess a source file
srcs/asm_srcs/opt_tokens.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/opt_tokens.c.i
.PHONY : srcs/asm_srcs/opt_tokens.c.i

srcs/asm_srcs/opt_tokens.s: srcs/asm_srcs/opt_tokens.c.s

.PHONY : srcs/asm_srcs/opt_tokens.s

# target to generate assembly for a file
srcs/asm_srcs/opt_tokens.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/opt_tokens.c.s
.PHONY : srcs/asm_srcs/opt_tokens.c.s

srcs/asm_srcs/parse_asm.o: srcs/asm_srcs/parse_asm.c.o

.PHONY : srcs/asm_srcs/parse_asm.o

# target to build an object file
srcs/asm_srcs/parse_asm.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_asm.c.o
.PHONY : srcs/asm_srcs/parse_asm.c.o

srcs/asm_srcs/parse_asm.i: srcs/asm_srcs/parse_asm.c.i

.PHONY : srcs/asm_srcs/parse_asm.i

# target to preprocess a source file
srcs/asm_srcs/parse_asm.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_asm.c.i
.PHONY : srcs/asm_srcs/parse_asm.c.i

srcs/asm_srcs/parse_asm.s: srcs/asm_srcs/parse_asm.c.s

.PHONY : srcs/asm_srcs/parse_asm.s

# target to generate assembly for a file
srcs/asm_srcs/parse_asm.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_asm.c.s
.PHONY : srcs/asm_srcs/parse_asm.c.s

srcs/asm_srcs/parse_opts.o: srcs/asm_srcs/parse_opts.c.o

.PHONY : srcs/asm_srcs/parse_opts.o

# target to build an object file
srcs/asm_srcs/parse_opts.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_opts.c.o
.PHONY : srcs/asm_srcs/parse_opts.c.o

srcs/asm_srcs/parse_opts.i: srcs/asm_srcs/parse_opts.c.i

.PHONY : srcs/asm_srcs/parse_opts.i

# target to preprocess a source file
srcs/asm_srcs/parse_opts.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_opts.c.i
.PHONY : srcs/asm_srcs/parse_opts.c.i

srcs/asm_srcs/parse_opts.s: srcs/asm_srcs/parse_opts.c.s

.PHONY : srcs/asm_srcs/parse_opts.s

# target to generate assembly for a file
srcs/asm_srcs/parse_opts.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/parse_opts.c.s
.PHONY : srcs/asm_srcs/parse_opts.c.s

srcs/asm_srcs/print.o: srcs/asm_srcs/print.c.o

.PHONY : srcs/asm_srcs/print.o

# target to build an object file
srcs/asm_srcs/print.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/print.c.o
.PHONY : srcs/asm_srcs/print.c.o

srcs/asm_srcs/print.i: srcs/asm_srcs/print.c.i

.PHONY : srcs/asm_srcs/print.i

# target to preprocess a source file
srcs/asm_srcs/print.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/print.c.i
.PHONY : srcs/asm_srcs/print.c.i

srcs/asm_srcs/print.s: srcs/asm_srcs/print.c.s

.PHONY : srcs/asm_srcs/print.s

# target to generate assembly for a file
srcs/asm_srcs/print.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/print.c.s
.PHONY : srcs/asm_srcs/print.c.s

srcs/asm_srcs/read_opts.o: srcs/asm_srcs/read_opts.c.o

.PHONY : srcs/asm_srcs/read_opts.o

# target to build an object file
srcs/asm_srcs/read_opts.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/read_opts.c.o
.PHONY : srcs/asm_srcs/read_opts.c.o

srcs/asm_srcs/read_opts.i: srcs/asm_srcs/read_opts.c.i

.PHONY : srcs/asm_srcs/read_opts.i

# target to preprocess a source file
srcs/asm_srcs/read_opts.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/read_opts.c.i
.PHONY : srcs/asm_srcs/read_opts.c.i

srcs/asm_srcs/read_opts.s: srcs/asm_srcs/read_opts.c.s

.PHONY : srcs/asm_srcs/read_opts.s

# target to generate assembly for a file
srcs/asm_srcs/read_opts.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/read_opts.c.s
.PHONY : srcs/asm_srcs/read_opts.c.s

srcs/asm_srcs/utils.o: srcs/asm_srcs/utils.c.o

.PHONY : srcs/asm_srcs/utils.o

# target to build an object file
srcs/asm_srcs/utils.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/utils.c.o
.PHONY : srcs/asm_srcs/utils.c.o

srcs/asm_srcs/utils.i: srcs/asm_srcs/utils.c.i

.PHONY : srcs/asm_srcs/utils.i

# target to preprocess a source file
srcs/asm_srcs/utils.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/utils.c.i
.PHONY : srcs/asm_srcs/utils.c.i

srcs/asm_srcs/utils.s: srcs/asm_srcs/utils.c.s

.PHONY : srcs/asm_srcs/utils.s

# target to generate assembly for a file
srcs/asm_srcs/utils.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/utils.c.s
.PHONY : srcs/asm_srcs/utils.c.s

srcs/asm_srcs/write.o: srcs/asm_srcs/write.c.o

.PHONY : srcs/asm_srcs/write.o

# target to build an object file
srcs/asm_srcs/write.c.o:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/write.c.o
.PHONY : srcs/asm_srcs/write.c.o

srcs/asm_srcs/write.i: srcs/asm_srcs/write.c.i

.PHONY : srcs/asm_srcs/write.i

# target to preprocess a source file
srcs/asm_srcs/write.c.i:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/write.c.i
.PHONY : srcs/asm_srcs/write.c.i

srcs/asm_srcs/write.s: srcs/asm_srcs/write.c.s

.PHONY : srcs/asm_srcs/write.s

# target to generate assembly for a file
srcs/asm_srcs/write.c.s:
	$(MAKE) -f CMakeFiles/asm.dir/build.make CMakeFiles/asm.dir/srcs/asm_srcs/write.c.s
.PHONY : srcs/asm_srcs/write.c.s

srcs/corewar_srcs/arena_ini.o: srcs/corewar_srcs/arena_ini.c.o

.PHONY : srcs/corewar_srcs/arena_ini.o

# target to build an object file
srcs/corewar_srcs/arena_ini.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/arena_ini.c.o
.PHONY : srcs/corewar_srcs/arena_ini.c.o

srcs/corewar_srcs/arena_ini.i: srcs/corewar_srcs/arena_ini.c.i

.PHONY : srcs/corewar_srcs/arena_ini.i

# target to preprocess a source file
srcs/corewar_srcs/arena_ini.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/arena_ini.c.i
.PHONY : srcs/corewar_srcs/arena_ini.c.i

srcs/corewar_srcs/arena_ini.s: srcs/corewar_srcs/arena_ini.c.s

.PHONY : srcs/corewar_srcs/arena_ini.s

# target to generate assembly for a file
srcs/corewar_srcs/arena_ini.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/arena_ini.c.s
.PHONY : srcs/corewar_srcs/arena_ini.c.s

srcs/corewar_srcs/check_process.o: srcs/corewar_srcs/check_process.c.o

.PHONY : srcs/corewar_srcs/check_process.o

# target to build an object file
srcs/corewar_srcs/check_process.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/check_process.c.o
.PHONY : srcs/corewar_srcs/check_process.c.o

srcs/corewar_srcs/check_process.i: srcs/corewar_srcs/check_process.c.i

.PHONY : srcs/corewar_srcs/check_process.i

# target to preprocess a source file
srcs/corewar_srcs/check_process.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/check_process.c.i
.PHONY : srcs/corewar_srcs/check_process.c.i

srcs/corewar_srcs/check_process.s: srcs/corewar_srcs/check_process.c.s

.PHONY : srcs/corewar_srcs/check_process.s

# target to generate assembly for a file
srcs/corewar_srcs/check_process.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/check_process.c.s
.PHONY : srcs/corewar_srcs/check_process.c.s

srcs/corewar_srcs/corewar.o: srcs/corewar_srcs/corewar.c.o

.PHONY : srcs/corewar_srcs/corewar.o

# target to build an object file
srcs/corewar_srcs/corewar.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/corewar.c.o
.PHONY : srcs/corewar_srcs/corewar.c.o

srcs/corewar_srcs/corewar.i: srcs/corewar_srcs/corewar.c.i

.PHONY : srcs/corewar_srcs/corewar.i

# target to preprocess a source file
srcs/corewar_srcs/corewar.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/corewar.c.i
.PHONY : srcs/corewar_srcs/corewar.c.i

srcs/corewar_srcs/corewar.s: srcs/corewar_srcs/corewar.c.s

.PHONY : srcs/corewar_srcs/corewar.s

# target to generate assembly for a file
srcs/corewar_srcs/corewar.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/corewar.c.s
.PHONY : srcs/corewar_srcs/corewar.c.s

srcs/corewar_srcs/gr_gen_tex.o: srcs/corewar_srcs/gr_gen_tex.c.o

.PHONY : srcs/corewar_srcs/gr_gen_tex.o

# target to build an object file
srcs/corewar_srcs/gr_gen_tex.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gen_tex.c.o
.PHONY : srcs/corewar_srcs/gr_gen_tex.c.o

srcs/corewar_srcs/gr_gen_tex.i: srcs/corewar_srcs/gr_gen_tex.c.i

.PHONY : srcs/corewar_srcs/gr_gen_tex.i

# target to preprocess a source file
srcs/corewar_srcs/gr_gen_tex.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gen_tex.c.i
.PHONY : srcs/corewar_srcs/gr_gen_tex.c.i

srcs/corewar_srcs/gr_gen_tex.s: srcs/corewar_srcs/gr_gen_tex.c.s

.PHONY : srcs/corewar_srcs/gr_gen_tex.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_gen_tex.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gen_tex.c.s
.PHONY : srcs/corewar_srcs/gr_gen_tex.c.s

srcs/corewar_srcs/gr_gl_buffer.o: srcs/corewar_srcs/gr_gl_buffer.c.o

.PHONY : srcs/corewar_srcs/gr_gl_buffer.o

# target to build an object file
srcs/corewar_srcs/gr_gl_buffer.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gl_buffer.c.o
.PHONY : srcs/corewar_srcs/gr_gl_buffer.c.o

srcs/corewar_srcs/gr_gl_buffer.i: srcs/corewar_srcs/gr_gl_buffer.c.i

.PHONY : srcs/corewar_srcs/gr_gl_buffer.i

# target to preprocess a source file
srcs/corewar_srcs/gr_gl_buffer.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gl_buffer.c.i
.PHONY : srcs/corewar_srcs/gr_gl_buffer.c.i

srcs/corewar_srcs/gr_gl_buffer.s: srcs/corewar_srcs/gr_gl_buffer.c.s

.PHONY : srcs/corewar_srcs/gr_gl_buffer.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_gl_buffer.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_gl_buffer.c.s
.PHONY : srcs/corewar_srcs/gr_gl_buffer.c.s

srcs/corewar_srcs/gr_vm_camera_handling.o: srcs/corewar_srcs/gr_vm_camera_handling.c.o

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.o

# target to build an object file
srcs/corewar_srcs/gr_vm_camera_handling.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling.c.o
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.c.o

srcs/corewar_srcs/gr_vm_camera_handling.i: srcs/corewar_srcs/gr_vm_camera_handling.c.i

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_camera_handling.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling.c.i
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.c.i

srcs/corewar_srcs/gr_vm_camera_handling.s: srcs/corewar_srcs/gr_vm_camera_handling.c.s

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_camera_handling.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling.c.s
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling.c.s

srcs/corewar_srcs/gr_vm_camera_handling_rot.o: srcs/corewar_srcs/gr_vm_camera_handling_rot.c.o

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.o

# target to build an object file
srcs/corewar_srcs/gr_vm_camera_handling_rot.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling_rot.c.o
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.c.o

srcs/corewar_srcs/gr_vm_camera_handling_rot.i: srcs/corewar_srcs/gr_vm_camera_handling_rot.c.i

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_camera_handling_rot.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling_rot.c.i
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.c.i

srcs/corewar_srcs/gr_vm_camera_handling_rot.s: srcs/corewar_srcs/gr_vm_camera_handling_rot.c.s

.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_camera_handling_rot.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_camera_handling_rot.c.s
.PHONY : srcs/corewar_srcs/gr_vm_camera_handling_rot.c.s

srcs/corewar_srcs/gr_vm_handlers.o: srcs/corewar_srcs/gr_vm_handlers.c.o

.PHONY : srcs/corewar_srcs/gr_vm_handlers.o

# target to build an object file
srcs/corewar_srcs/gr_vm_handlers.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_handlers.c.o
.PHONY : srcs/corewar_srcs/gr_vm_handlers.c.o

srcs/corewar_srcs/gr_vm_handlers.i: srcs/corewar_srcs/gr_vm_handlers.c.i

.PHONY : srcs/corewar_srcs/gr_vm_handlers.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_handlers.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_handlers.c.i
.PHONY : srcs/corewar_srcs/gr_vm_handlers.c.i

srcs/corewar_srcs/gr_vm_handlers.s: srcs/corewar_srcs/gr_vm_handlers.c.s

.PHONY : srcs/corewar_srcs/gr_vm_handlers.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_handlers.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_handlers.c.s
.PHONY : srcs/corewar_srcs/gr_vm_handlers.c.s

srcs/corewar_srcs/gr_vm_init.o: srcs/corewar_srcs/gr_vm_init.c.o

.PHONY : srcs/corewar_srcs/gr_vm_init.o

# target to build an object file
srcs/corewar_srcs/gr_vm_init.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init.c.o
.PHONY : srcs/corewar_srcs/gr_vm_init.c.o

srcs/corewar_srcs/gr_vm_init.i: srcs/corewar_srcs/gr_vm_init.c.i

.PHONY : srcs/corewar_srcs/gr_vm_init.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_init.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init.c.i
.PHONY : srcs/corewar_srcs/gr_vm_init.c.i

srcs/corewar_srcs/gr_vm_init.s: srcs/corewar_srcs/gr_vm_init.c.s

.PHONY : srcs/corewar_srcs/gr_vm_init.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_init.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init.c.s
.PHONY : srcs/corewar_srcs/gr_vm_init.c.s

srcs/corewar_srcs/gr_vm_init_cube.o: srcs/corewar_srcs/gr_vm_init_cube.c.o

.PHONY : srcs/corewar_srcs/gr_vm_init_cube.o

# target to build an object file
srcs/corewar_srcs/gr_vm_init_cube.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init_cube.c.o
.PHONY : srcs/corewar_srcs/gr_vm_init_cube.c.o

srcs/corewar_srcs/gr_vm_init_cube.i: srcs/corewar_srcs/gr_vm_init_cube.c.i

.PHONY : srcs/corewar_srcs/gr_vm_init_cube.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_init_cube.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init_cube.c.i
.PHONY : srcs/corewar_srcs/gr_vm_init_cube.c.i

srcs/corewar_srcs/gr_vm_init_cube.s: srcs/corewar_srcs/gr_vm_init_cube.c.s

.PHONY : srcs/corewar_srcs/gr_vm_init_cube.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_init_cube.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_init_cube.c.s
.PHONY : srcs/corewar_srcs/gr_vm_init_cube.c.s

srcs/corewar_srcs/gr_vm_inputs.o: srcs/corewar_srcs/gr_vm_inputs.c.o

.PHONY : srcs/corewar_srcs/gr_vm_inputs.o

# target to build an object file
srcs/corewar_srcs/gr_vm_inputs.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_inputs.c.o
.PHONY : srcs/corewar_srcs/gr_vm_inputs.c.o

srcs/corewar_srcs/gr_vm_inputs.i: srcs/corewar_srcs/gr_vm_inputs.c.i

.PHONY : srcs/corewar_srcs/gr_vm_inputs.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_inputs.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_inputs.c.i
.PHONY : srcs/corewar_srcs/gr_vm_inputs.c.i

srcs/corewar_srcs/gr_vm_inputs.s: srcs/corewar_srcs/gr_vm_inputs.c.s

.PHONY : srcs/corewar_srcs/gr_vm_inputs.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_inputs.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_inputs.c.s
.PHONY : srcs/corewar_srcs/gr_vm_inputs.c.s

srcs/corewar_srcs/gr_vm_load_texture.o: srcs/corewar_srcs/gr_vm_load_texture.c.o

.PHONY : srcs/corewar_srcs/gr_vm_load_texture.o

# target to build an object file
srcs/corewar_srcs/gr_vm_load_texture.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_load_texture.c.o
.PHONY : srcs/corewar_srcs/gr_vm_load_texture.c.o

srcs/corewar_srcs/gr_vm_load_texture.i: srcs/corewar_srcs/gr_vm_load_texture.c.i

.PHONY : srcs/corewar_srcs/gr_vm_load_texture.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_load_texture.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_load_texture.c.i
.PHONY : srcs/corewar_srcs/gr_vm_load_texture.c.i

srcs/corewar_srcs/gr_vm_load_texture.s: srcs/corewar_srcs/gr_vm_load_texture.c.s

.PHONY : srcs/corewar_srcs/gr_vm_load_texture.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_load_texture.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_load_texture.c.s
.PHONY : srcs/corewar_srcs/gr_vm_load_texture.c.s

srcs/corewar_srcs/gr_vm_matrix.o: srcs/corewar_srcs/gr_vm_matrix.c.o

.PHONY : srcs/corewar_srcs/gr_vm_matrix.o

# target to build an object file
srcs/corewar_srcs/gr_vm_matrix.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_matrix.c.o
.PHONY : srcs/corewar_srcs/gr_vm_matrix.c.o

srcs/corewar_srcs/gr_vm_matrix.i: srcs/corewar_srcs/gr_vm_matrix.c.i

.PHONY : srcs/corewar_srcs/gr_vm_matrix.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_matrix.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_matrix.c.i
.PHONY : srcs/corewar_srcs/gr_vm_matrix.c.i

srcs/corewar_srcs/gr_vm_matrix.s: srcs/corewar_srcs/gr_vm_matrix.c.s

.PHONY : srcs/corewar_srcs/gr_vm_matrix.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_matrix.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_matrix.c.s
.PHONY : srcs/corewar_srcs/gr_vm_matrix.c.s

srcs/corewar_srcs/gr_vm_render_opengl.o: srcs/corewar_srcs/gr_vm_render_opengl.c.o

.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.o

# target to build an object file
srcs/corewar_srcs/gr_vm_render_opengl.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_render_opengl.c.o
.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.c.o

srcs/corewar_srcs/gr_vm_render_opengl.i: srcs/corewar_srcs/gr_vm_render_opengl.c.i

.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_render_opengl.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_render_opengl.c.i
.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.c.i

srcs/corewar_srcs/gr_vm_render_opengl.s: srcs/corewar_srcs/gr_vm_render_opengl.c.s

.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_render_opengl.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_render_opengl.c.s
.PHONY : srcs/corewar_srcs/gr_vm_render_opengl.c.s

srcs/corewar_srcs/gr_vm_run.o: srcs/corewar_srcs/gr_vm_run.c.o

.PHONY : srcs/corewar_srcs/gr_vm_run.o

# target to build an object file
srcs/corewar_srcs/gr_vm_run.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_run.c.o
.PHONY : srcs/corewar_srcs/gr_vm_run.c.o

srcs/corewar_srcs/gr_vm_run.i: srcs/corewar_srcs/gr_vm_run.c.i

.PHONY : srcs/corewar_srcs/gr_vm_run.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_run.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_run.c.i
.PHONY : srcs/corewar_srcs/gr_vm_run.c.i

srcs/corewar_srcs/gr_vm_run.s: srcs/corewar_srcs/gr_vm_run.c.s

.PHONY : srcs/corewar_srcs/gr_vm_run.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_run.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_run.c.s
.PHONY : srcs/corewar_srcs/gr_vm_run.c.s

srcs/corewar_srcs/gr_vm_ui.o: srcs/corewar_srcs/gr_vm_ui.c.o

.PHONY : srcs/corewar_srcs/gr_vm_ui.o

# target to build an object file
srcs/corewar_srcs/gr_vm_ui.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_ui.c.o
.PHONY : srcs/corewar_srcs/gr_vm_ui.c.o

srcs/corewar_srcs/gr_vm_ui.i: srcs/corewar_srcs/gr_vm_ui.c.i

.PHONY : srcs/corewar_srcs/gr_vm_ui.i

# target to preprocess a source file
srcs/corewar_srcs/gr_vm_ui.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_ui.c.i
.PHONY : srcs/corewar_srcs/gr_vm_ui.c.i

srcs/corewar_srcs/gr_vm_ui.s: srcs/corewar_srcs/gr_vm_ui.c.s

.PHONY : srcs/corewar_srcs/gr_vm_ui.s

# target to generate assembly for a file
srcs/corewar_srcs/gr_vm_ui.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/gr_vm_ui.c.s
.PHONY : srcs/corewar_srcs/gr_vm_ui.c.s

srcs/corewar_srcs/ins_basic.o: srcs/corewar_srcs/ins_basic.c.o

.PHONY : srcs/corewar_srcs/ins_basic.o

# target to build an object file
srcs/corewar_srcs/ins_basic.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_basic.c.o
.PHONY : srcs/corewar_srcs/ins_basic.c.o

srcs/corewar_srcs/ins_basic.i: srcs/corewar_srcs/ins_basic.c.i

.PHONY : srcs/corewar_srcs/ins_basic.i

# target to preprocess a source file
srcs/corewar_srcs/ins_basic.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_basic.c.i
.PHONY : srcs/corewar_srcs/ins_basic.c.i

srcs/corewar_srcs/ins_basic.s: srcs/corewar_srcs/ins_basic.c.s

.PHONY : srcs/corewar_srcs/ins_basic.s

# target to generate assembly for a file
srcs/corewar_srcs/ins_basic.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_basic.c.s
.PHONY : srcs/corewar_srcs/ins_basic.c.s

srcs/corewar_srcs/ins_calc.o: srcs/corewar_srcs/ins_calc.c.o

.PHONY : srcs/corewar_srcs/ins_calc.o

# target to build an object file
srcs/corewar_srcs/ins_calc.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_calc.c.o
.PHONY : srcs/corewar_srcs/ins_calc.c.o

srcs/corewar_srcs/ins_calc.i: srcs/corewar_srcs/ins_calc.c.i

.PHONY : srcs/corewar_srcs/ins_calc.i

# target to preprocess a source file
srcs/corewar_srcs/ins_calc.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_calc.c.i
.PHONY : srcs/corewar_srcs/ins_calc.c.i

srcs/corewar_srcs/ins_calc.s: srcs/corewar_srcs/ins_calc.c.s

.PHONY : srcs/corewar_srcs/ins_calc.s

# target to generate assembly for a file
srcs/corewar_srcs/ins_calc.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_calc.c.s
.PHONY : srcs/corewar_srcs/ins_calc.c.s

srcs/corewar_srcs/ins_fork.o: srcs/corewar_srcs/ins_fork.c.o

.PHONY : srcs/corewar_srcs/ins_fork.o

# target to build an object file
srcs/corewar_srcs/ins_fork.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_fork.c.o
.PHONY : srcs/corewar_srcs/ins_fork.c.o

srcs/corewar_srcs/ins_fork.i: srcs/corewar_srcs/ins_fork.c.i

.PHONY : srcs/corewar_srcs/ins_fork.i

# target to preprocess a source file
srcs/corewar_srcs/ins_fork.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_fork.c.i
.PHONY : srcs/corewar_srcs/ins_fork.c.i

srcs/corewar_srcs/ins_fork.s: srcs/corewar_srcs/ins_fork.c.s

.PHONY : srcs/corewar_srcs/ins_fork.s

# target to generate assembly for a file
srcs/corewar_srcs/ins_fork.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_fork.c.s
.PHONY : srcs/corewar_srcs/ins_fork.c.s

srcs/corewar_srcs/ins_index.o: srcs/corewar_srcs/ins_index.c.o

.PHONY : srcs/corewar_srcs/ins_index.o

# target to build an object file
srcs/corewar_srcs/ins_index.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_index.c.o
.PHONY : srcs/corewar_srcs/ins_index.c.o

srcs/corewar_srcs/ins_index.i: srcs/corewar_srcs/ins_index.c.i

.PHONY : srcs/corewar_srcs/ins_index.i

# target to preprocess a source file
srcs/corewar_srcs/ins_index.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_index.c.i
.PHONY : srcs/corewar_srcs/ins_index.c.i

srcs/corewar_srcs/ins_index.s: srcs/corewar_srcs/ins_index.c.s

.PHONY : srcs/corewar_srcs/ins_index.s

# target to generate assembly for a file
srcs/corewar_srcs/ins_index.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/ins_index.c.s
.PHONY : srcs/corewar_srcs/ins_index.c.s

srcs/corewar_srcs/mem.o: srcs/corewar_srcs/mem.c.o

.PHONY : srcs/corewar_srcs/mem.o

# target to build an object file
srcs/corewar_srcs/mem.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/mem.c.o
.PHONY : srcs/corewar_srcs/mem.c.o

srcs/corewar_srcs/mem.i: srcs/corewar_srcs/mem.c.i

.PHONY : srcs/corewar_srcs/mem.i

# target to preprocess a source file
srcs/corewar_srcs/mem.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/mem.c.i
.PHONY : srcs/corewar_srcs/mem.c.i

srcs/corewar_srcs/mem.s: srcs/corewar_srcs/mem.c.s

.PHONY : srcs/corewar_srcs/mem.s

# target to generate assembly for a file
srcs/corewar_srcs/mem.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/mem.c.s
.PHONY : srcs/corewar_srcs/mem.c.s

srcs/corewar_srcs/op.o: srcs/corewar_srcs/op.c.o

.PHONY : srcs/corewar_srcs/op.o

# target to build an object file
srcs/corewar_srcs/op.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/op.c.o
.PHONY : srcs/corewar_srcs/op.c.o

srcs/corewar_srcs/op.i: srcs/corewar_srcs/op.c.i

.PHONY : srcs/corewar_srcs/op.i

# target to preprocess a source file
srcs/corewar_srcs/op.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/op.c.i
.PHONY : srcs/corewar_srcs/op.c.i

srcs/corewar_srcs/op.s: srcs/corewar_srcs/op.c.s

.PHONY : srcs/corewar_srcs/op.s

# target to generate assembly for a file
srcs/corewar_srcs/op.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/op.c.s
.PHONY : srcs/corewar_srcs/op.c.s

srcs/corewar_srcs/options.o: srcs/corewar_srcs/options.c.o

.PHONY : srcs/corewar_srcs/options.o

# target to build an object file
srcs/corewar_srcs/options.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/options.c.o
.PHONY : srcs/corewar_srcs/options.c.o

srcs/corewar_srcs/options.i: srcs/corewar_srcs/options.c.i

.PHONY : srcs/corewar_srcs/options.i

# target to preprocess a source file
srcs/corewar_srcs/options.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/options.c.i
.PHONY : srcs/corewar_srcs/options.c.i

srcs/corewar_srcs/options.s: srcs/corewar_srcs/options.c.s

.PHONY : srcs/corewar_srcs/options.s

# target to generate assembly for a file
srcs/corewar_srcs/options.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/options.c.s
.PHONY : srcs/corewar_srcs/options.c.s

srcs/corewar_srcs/opts_tokens.o: srcs/corewar_srcs/opts_tokens.c.o

.PHONY : srcs/corewar_srcs/opts_tokens.o

# target to build an object file
srcs/corewar_srcs/opts_tokens.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/opts_tokens.c.o
.PHONY : srcs/corewar_srcs/opts_tokens.c.o

srcs/corewar_srcs/opts_tokens.i: srcs/corewar_srcs/opts_tokens.c.i

.PHONY : srcs/corewar_srcs/opts_tokens.i

# target to preprocess a source file
srcs/corewar_srcs/opts_tokens.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/opts_tokens.c.i
.PHONY : srcs/corewar_srcs/opts_tokens.c.i

srcs/corewar_srcs/opts_tokens.s: srcs/corewar_srcs/opts_tokens.c.s

.PHONY : srcs/corewar_srcs/opts_tokens.s

# target to generate assembly for a file
srcs/corewar_srcs/opts_tokens.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/opts_tokens.c.s
.PHONY : srcs/corewar_srcs/opts_tokens.c.s

srcs/corewar_srcs/parse_args.o: srcs/corewar_srcs/parse_args.c.o

.PHONY : srcs/corewar_srcs/parse_args.o

# target to build an object file
srcs/corewar_srcs/parse_args.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/parse_args.c.o
.PHONY : srcs/corewar_srcs/parse_args.c.o

srcs/corewar_srcs/parse_args.i: srcs/corewar_srcs/parse_args.c.i

.PHONY : srcs/corewar_srcs/parse_args.i

# target to preprocess a source file
srcs/corewar_srcs/parse_args.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/parse_args.c.i
.PHONY : srcs/corewar_srcs/parse_args.c.i

srcs/corewar_srcs/parse_args.s: srcs/corewar_srcs/parse_args.c.s

.PHONY : srcs/corewar_srcs/parse_args.s

# target to generate assembly for a file
srcs/corewar_srcs/parse_args.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/parse_args.c.s
.PHONY : srcs/corewar_srcs/parse_args.c.s

srcs/corewar_srcs/process.o: srcs/corewar_srcs/process.c.o

.PHONY : srcs/corewar_srcs/process.o

# target to build an object file
srcs/corewar_srcs/process.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/process.c.o
.PHONY : srcs/corewar_srcs/process.c.o

srcs/corewar_srcs/process.i: srcs/corewar_srcs/process.c.i

.PHONY : srcs/corewar_srcs/process.i

# target to preprocess a source file
srcs/corewar_srcs/process.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/process.c.i
.PHONY : srcs/corewar_srcs/process.c.i

srcs/corewar_srcs/process.s: srcs/corewar_srcs/process.c.s

.PHONY : srcs/corewar_srcs/process.s

# target to generate assembly for a file
srcs/corewar_srcs/process.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/process.c.s
.PHONY : srcs/corewar_srcs/process.c.s

srcs/corewar_srcs/read_args.o: srcs/corewar_srcs/read_args.c.o

.PHONY : srcs/corewar_srcs/read_args.o

# target to build an object file
srcs/corewar_srcs/read_args.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/read_args.c.o
.PHONY : srcs/corewar_srcs/read_args.c.o

srcs/corewar_srcs/read_args.i: srcs/corewar_srcs/read_args.c.i

.PHONY : srcs/corewar_srcs/read_args.i

# target to preprocess a source file
srcs/corewar_srcs/read_args.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/read_args.c.i
.PHONY : srcs/corewar_srcs/read_args.c.i

srcs/corewar_srcs/read_args.s: srcs/corewar_srcs/read_args.c.s

.PHONY : srcs/corewar_srcs/read_args.s

# target to generate assembly for a file
srcs/corewar_srcs/read_args.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/read_args.c.s
.PHONY : srcs/corewar_srcs/read_args.c.s

srcs/corewar_srcs/utils.o: srcs/corewar_srcs/utils.c.o

.PHONY : srcs/corewar_srcs/utils.o

# target to build an object file
srcs/corewar_srcs/utils.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/utils.c.o
.PHONY : srcs/corewar_srcs/utils.c.o

srcs/corewar_srcs/utils.i: srcs/corewar_srcs/utils.c.i

.PHONY : srcs/corewar_srcs/utils.i

# target to preprocess a source file
srcs/corewar_srcs/utils.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/utils.c.i
.PHONY : srcs/corewar_srcs/utils.c.i

srcs/corewar_srcs/utils.s: srcs/corewar_srcs/utils.c.s

.PHONY : srcs/corewar_srcs/utils.s

# target to generate assembly for a file
srcs/corewar_srcs/utils.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/utils.c.s
.PHONY : srcs/corewar_srcs/utils.c.s

srcs/corewar_srcs/values.o: srcs/corewar_srcs/values.c.o

.PHONY : srcs/corewar_srcs/values.o

# target to build an object file
srcs/corewar_srcs/values.c.o:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/values.c.o
.PHONY : srcs/corewar_srcs/values.c.o

srcs/corewar_srcs/values.i: srcs/corewar_srcs/values.c.i

.PHONY : srcs/corewar_srcs/values.i

# target to preprocess a source file
srcs/corewar_srcs/values.c.i:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/values.c.i
.PHONY : srcs/corewar_srcs/values.c.i

srcs/corewar_srcs/values.s: srcs/corewar_srcs/values.c.s

.PHONY : srcs/corewar_srcs/values.s

# target to generate assembly for a file
srcs/corewar_srcs/values.c.s:
	$(MAKE) -f CMakeFiles/corewar.dir/build.make CMakeFiles/corewar.dir/srcs/corewar_srcs/values.c.s
.PHONY : srcs/corewar_srcs/values.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... asm"
	@echo "... corewar"
	@echo "... srcs/asm_srcs/asm.o"
	@echo "... srcs/asm_srcs/asm.i"
	@echo "... srcs/asm_srcs/asm.s"
	@echo "... srcs/asm_srcs/asm_tokens.o"
	@echo "... srcs/asm_srcs/asm_tokens.i"
	@echo "... srcs/asm_srcs/asm_tokens.s"
	@echo "... srcs/asm_srcs/compile.o"
	@echo "... srcs/asm_srcs/compile.i"
	@echo "... srcs/asm_srcs/compile.s"
	@echo "... srcs/asm_srcs/op.o"
	@echo "... srcs/asm_srcs/op.i"
	@echo "... srcs/asm_srcs/op.s"
	@echo "... srcs/asm_srcs/opt_tokens.o"
	@echo "... srcs/asm_srcs/opt_tokens.i"
	@echo "... srcs/asm_srcs/opt_tokens.s"
	@echo "... srcs/asm_srcs/parse_asm.o"
	@echo "... srcs/asm_srcs/parse_asm.i"
	@echo "... srcs/asm_srcs/parse_asm.s"
	@echo "... srcs/asm_srcs/parse_opts.o"
	@echo "... srcs/asm_srcs/parse_opts.i"
	@echo "... srcs/asm_srcs/parse_opts.s"
	@echo "... srcs/asm_srcs/print.o"
	@echo "... srcs/asm_srcs/print.i"
	@echo "... srcs/asm_srcs/print.s"
	@echo "... srcs/asm_srcs/read_opts.o"
	@echo "... srcs/asm_srcs/read_opts.i"
	@echo "... srcs/asm_srcs/read_opts.s"
	@echo "... srcs/asm_srcs/utils.o"
	@echo "... srcs/asm_srcs/utils.i"
	@echo "... srcs/asm_srcs/utils.s"
	@echo "... srcs/asm_srcs/write.o"
	@echo "... srcs/asm_srcs/write.i"
	@echo "... srcs/asm_srcs/write.s"
	@echo "... srcs/corewar_srcs/arena_ini.o"
	@echo "... srcs/corewar_srcs/arena_ini.i"
	@echo "... srcs/corewar_srcs/arena_ini.s"
	@echo "... srcs/corewar_srcs/check_process.o"
	@echo "... srcs/corewar_srcs/check_process.i"
	@echo "... srcs/corewar_srcs/check_process.s"
	@echo "... srcs/corewar_srcs/corewar.o"
	@echo "... srcs/corewar_srcs/corewar.i"
	@echo "... srcs/corewar_srcs/corewar.s"
	@echo "... srcs/corewar_srcs/gr_gen_tex.o"
	@echo "... srcs/corewar_srcs/gr_gen_tex.i"
	@echo "... srcs/corewar_srcs/gr_gen_tex.s"
	@echo "... srcs/corewar_srcs/gr_gl_buffer.o"
	@echo "... srcs/corewar_srcs/gr_gl_buffer.i"
	@echo "... srcs/corewar_srcs/gr_gl_buffer.s"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling.o"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling.i"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling.s"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling_rot.o"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling_rot.i"
	@echo "... srcs/corewar_srcs/gr_vm_camera_handling_rot.s"
	@echo "... srcs/corewar_srcs/gr_vm_handlers.o"
	@echo "... srcs/corewar_srcs/gr_vm_handlers.i"
	@echo "... srcs/corewar_srcs/gr_vm_handlers.s"
	@echo "... srcs/corewar_srcs/gr_vm_init.o"
	@echo "... srcs/corewar_srcs/gr_vm_init.i"
	@echo "... srcs/corewar_srcs/gr_vm_init.s"
	@echo "... srcs/corewar_srcs/gr_vm_init_cube.o"
	@echo "... srcs/corewar_srcs/gr_vm_init_cube.i"
	@echo "... srcs/corewar_srcs/gr_vm_init_cube.s"
	@echo "... srcs/corewar_srcs/gr_vm_inputs.o"
	@echo "... srcs/corewar_srcs/gr_vm_inputs.i"
	@echo "... srcs/corewar_srcs/gr_vm_inputs.s"
	@echo "... srcs/corewar_srcs/gr_vm_load_texture.o"
	@echo "... srcs/corewar_srcs/gr_vm_load_texture.i"
	@echo "... srcs/corewar_srcs/gr_vm_load_texture.s"
	@echo "... srcs/corewar_srcs/gr_vm_matrix.o"
	@echo "... srcs/corewar_srcs/gr_vm_matrix.i"
	@echo "... srcs/corewar_srcs/gr_vm_matrix.s"
	@echo "... srcs/corewar_srcs/gr_vm_render_opengl.o"
	@echo "... srcs/corewar_srcs/gr_vm_render_opengl.i"
	@echo "... srcs/corewar_srcs/gr_vm_render_opengl.s"
	@echo "... srcs/corewar_srcs/gr_vm_run.o"
	@echo "... srcs/corewar_srcs/gr_vm_run.i"
	@echo "... srcs/corewar_srcs/gr_vm_run.s"
	@echo "... srcs/corewar_srcs/gr_vm_ui.o"
	@echo "... srcs/corewar_srcs/gr_vm_ui.i"
	@echo "... srcs/corewar_srcs/gr_vm_ui.s"
	@echo "... srcs/corewar_srcs/ins_basic.o"
	@echo "... srcs/corewar_srcs/ins_basic.i"
	@echo "... srcs/corewar_srcs/ins_basic.s"
	@echo "... srcs/corewar_srcs/ins_calc.o"
	@echo "... srcs/corewar_srcs/ins_calc.i"
	@echo "... srcs/corewar_srcs/ins_calc.s"
	@echo "... srcs/corewar_srcs/ins_fork.o"
	@echo "... srcs/corewar_srcs/ins_fork.i"
	@echo "... srcs/corewar_srcs/ins_fork.s"
	@echo "... srcs/corewar_srcs/ins_index.o"
	@echo "... srcs/corewar_srcs/ins_index.i"
	@echo "... srcs/corewar_srcs/ins_index.s"
	@echo "... srcs/corewar_srcs/mem.o"
	@echo "... srcs/corewar_srcs/mem.i"
	@echo "... srcs/corewar_srcs/mem.s"
	@echo "... srcs/corewar_srcs/op.o"
	@echo "... srcs/corewar_srcs/op.i"
	@echo "... srcs/corewar_srcs/op.s"
	@echo "... srcs/corewar_srcs/options.o"
	@echo "... srcs/corewar_srcs/options.i"
	@echo "... srcs/corewar_srcs/options.s"
	@echo "... srcs/corewar_srcs/opts_tokens.o"
	@echo "... srcs/corewar_srcs/opts_tokens.i"
	@echo "... srcs/corewar_srcs/opts_tokens.s"
	@echo "... srcs/corewar_srcs/parse_args.o"
	@echo "... srcs/corewar_srcs/parse_args.i"
	@echo "... srcs/corewar_srcs/parse_args.s"
	@echo "... srcs/corewar_srcs/process.o"
	@echo "... srcs/corewar_srcs/process.i"
	@echo "... srcs/corewar_srcs/process.s"
	@echo "... srcs/corewar_srcs/read_args.o"
	@echo "... srcs/corewar_srcs/read_args.i"
	@echo "... srcs/corewar_srcs/read_args.s"
	@echo "... srcs/corewar_srcs/utils.o"
	@echo "... srcs/corewar_srcs/utils.i"
	@echo "... srcs/corewar_srcs/utils.s"
	@echo "... srcs/corewar_srcs/values.o"
	@echo "... srcs/corewar_srcs/values.i"
	@echo "... srcs/corewar_srcs/values.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

